SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE actor_content;
TRUNCATE TABLE tv_shows_directors;
TRUNCATE TABLE review;
TRUNCATE TABLE movie;
TRUNCATE TABLE tv_show;
TRUNCATE TABLE content;
TRUNCATE TABLE actor;
TRUNCATE TABLE director;
TRUNCATE TABLE app_user;

SET FOREIGN_KEY_CHECKS = 1;
